"""Safely added res_id using batch mode

Revision ID: 1ef863485267
Revises: ad2bdc2c3c51
Create Date: 2026-05-23 14:07:45.085899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef863485267'
down_revision = 'ad2bdc2c3c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_res_id_resources'), 'resources', ['res_id'], ['res_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_res_id_resources'), type_='foreignkey')
        batch_op.drop_column('res_id')

    # ### end Alembic commands ###
