"""Added credits column with server default

Revision ID: ad2bdc2c3c51
Revises: 
Create Date: 2026-05-12 12:34:30.970369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2bdc2c3c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_resources')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credits')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('_alembic_tmp_resources',
    sa.Column('res_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=False),
    sa.Column('Description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('token', sa.INTEGER(), nullable=False),
    sa.Column('Status', sa.VARCHAR(), nullable=True),
    sa.Column('img', sa.VARCHAR(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('res_id')
    )
    # ### end Alembic commands ###
